### PR TITLE
Provide the filename as an argument to onFileLoaded

### PR DESCRIPTION
**Pull request by kulor**
We need this in a project we're working on so thought it worth back-porting it to the project

### CODE REVIEW

**Comment by nzambello** [comment]
Hi @kulor, thank you for contributing.
This feature is interesting and very useful.

**Comment by kulor** [comment]
@nzambello would you be able to publish this to NPM?

**Comment by nzambello** [comment]
Yep, I was waiting for the other PR, but now I can release this on npm.

**Comment by nzambello** [comment]
@kulor Released version 0.3.0 on [npm](https://www.npmjs.com/package/react-csv-reader/v/0.3.0).
Good job, thank you.

**Pull request merged**
